Feature: Added edit button
FidelityInternational/djangocms-navigation pull request #107
Opened 2022-02-24 14:49 UTC by adam-murray

2022-02-24 16:56 UTC, Bernardvdv approved these changes
looks good to me

2022-02-28 14:46 UTC, Aiky30 requested changes

2022-02-28 14:46 UTC, Aiky30 commented on CHANGELOG.rst
> +* MenuItem edit button added as list action button
Changelog is in the wrong place. 1.0.0 is already released

2022-02-28 15:07 UTC, Aiky30 approved these changes

2022-03-01 11:15 UTC, merged