Feature: Disable dropdown actions for MenuContentAdmin
FidelityInternational/djangocms-navigation pull request #110
Opened 2022-02-28 14:24 UTC by adam-murray

2022-02-28 14:36 UTC, Aiky30 requested changes

2022-02-28 14:36 UTC, Aiky30 commented on CHANGELOG.rst
> +* MenuContent dropdown actions removed
Changelog entry is in the wrong place

2022-02-28 15:08 UTC, Aiky30 approved these changes

2022-03-01 08:40 UTC, Bernardvdv approved these changes

2022-03-01 11:58 UTC, merged