Update Navigation menu tags to render correct breadcrumbs .
FidelityInternational/djangocms-navigation pull request #83
Opened 2020-08-21 09:00 UTC by NarenderRajuB

Feature/opencms 932:
1. Add is_home attribute to the Menu item node.
2. Update show breadcrumb navigation for navigation to ignore empty content navigation nodes

2020-08-24 15:13 UTC, Aiky30 requested changes

2020-08-24 16:07 UTC, NarenderRajuB commented on tests/test_cms_menus.py
> +               bbb
Updated . please review

2020-08-24 16:07 UTC, NarenderRajuB commented on tests/test_cms_menus.py
> +        tpl = Template("{% load navigation_menu_tags %}{% show_breadcrumb %}")
renamed to navigation_breadcrumb

2020-08-24 16:10 UTC, NarenderRajuB commented on djangocms_navigation/templatetags/navigation_menu_tags.py
> +class ShowBreadcrumb(InclusionTag):
Updated please review

2020-08-24 16:24 UTC, Aiky30 requested changes

2020-08-24 16:24 UTC, Aiky30 commented on djangocms_navigation/templatetags/navigation_menu_tags.py
> +class Navigation_ShowBreadcrumb(InclusionTag):
Violates PEP 008 naming where a class name should be upper cased words. Needs to be changed to: NavigationBreadcrumb

2020-08-24 16:24 UTC, Aiky30 commented on tests/test_cms_menus.py
> +            show_navigation_breadcrumb will return all the parents of the selected navigation node and home page
The tag name is: navigation_breadcrumb

2020-08-25 09:09 UTC, Aiky30 approved these changes

2020-08-25 09:11 UTC, merged